# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.FileField(upload_to='images/')),
                ('textFile', models.FileField(upload_to='texts/')),
            ],
        ),
    ]
