# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 10:44
from __future__ import unicode_literals

import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='imageFile',
            field=models.FileField(storage=app.storage.OverwriteStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='textFile',
            field=models.FileField(storage=app.storage.OverwriteStorage(), upload_to='texts/'),
        ),
    ]
